#!/bin/bash

set -e -x
#apt-get install -y curl

BUILT_RESOURCE=$PWD/built-resource

export GOPATH=$PWD/gopath

cd $(dirname $0)/../..

export GOPATH=$PWD/Godeps/_workspace:$GOPATH
export PATH=${PWD}/Godeps/_workspace/bin:$PATH

go install github.com/onsi/ginkgo/ginkgo

CGO_ENABLED=1 ginkgo -r -p

go build -o ./assets/check ./cmd/check/
go build -o ./assets/print-metadata ./cmd/print-metadata/

mkdir docker
cd docker
curl -k -sSL -O https://master.dockerproject.org/linux/ppc64le/dockerd
curl -k -sSL -O https://master.dockerproject.org/linux/ppc64le/docker-proxy
curl -k -sSL -O https://master.dockerproject.org/linux/ppc64le/docker-runc
curl -k -sSL -O https://master.dockerproject.org/linux/ppc64le/docker
curl -k -sSL -O https://master.dockerproject.org/linux/ppc64le/docker-containerd
curl -k -sSL -O https://master.dockerproject.org/linux/ppc64le/docker-containerd-shim

chmod +x *
cd ..

cp -a ./* ${BUILT_RESOURCE}/
