---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: 140.211.168.97:5000/golang1.6
    insecure_registries: ["140.211.168.97:5000"]

inputs:
- name: docker-image-resource
  path: gopath/src/github.com/concourse/docker-image-resource

outputs:
- name: built-resource

run:
  path: gopath/src/github.com/concourse/docker-image-resource/ci/scripts/build
